language: python

git:
  depth: false

branches:
  only:
    - master
    - dev

install:
  - pip install --upgrade numpy

script:
  - ./tests/runTests.py -d # default config
  - ./tests/runTests.py -f # run tests, returning error code
