language: python

python:
  - "2.7"
  - "3.5"
  - "3.7"

git:
  depth: false

branches:
  only:
    - master
    - dev

jobs:
  include:
      - install:
          - pip install pyyaml
        script:
          - export PYTHONPATH=$PWD:$PYTHONPATH
          - sh -c "cd tests && ./minisciath/minisciath.py tests.yml --only-group default_configuration"
      - install:
          - pip install pylint
        script: sh -c "pylint --errors-only sciath/*.py tests/test_data/*/*.py"
      - install:
          - pip install pylint
        script:
          - sh -c "pylint sciath/*.py"
