language: python

git:
  depth: false

branches:
  only:
    - master
    - dev

install:
  - pip install numpy

script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - ./tests/run_tests.py -d # default config
  - yes | ./tests/run_tests.py -f # run tests, returning error code
