language: python

git:
  depth: false

branches:
  only:
    - master
    - dev

install:
  - pip install numpy pytest

script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - ./tests/runTests.py -d # default config
  - yes | ./tests/runTests.py -f # run tests, returning error code
  - python -m pytest tests/enum23/test_enum23.py
