language: python

python:
  - "2.7"
  - "3.5"
  - "3.7"

git:
  depth: false

branches:
  only:
    - master
    - dev

install:
  - pip install pyyaml pylint

script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - cd tests && ./run_tests.sh && cd ..
  - cd sciath && ls | grep '.py$' | xargs pylint --errors-only && cd ..
