language: python

git:
  depth: false

branches:
  only:
    - master
    - dev

stages:
    - lint errors
    - test
    - lint all

jobs:
  include:
    - stage: test
      python: 2.7
      install:
        - pip install pyyaml
      script:
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - sh -c "cd tests && ./minisciath/minisciath.py tests.yml --only-group default_configuration"
    - stage: test
      python: 3.5
      install:
        - pip install pyyaml
      script:
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - sh -c "cd tests && ./minisciath/minisciath.py tests.yml --only-group default_configuration"
    - stage: test
      python: 3.7
      install:
        - pip install pyyaml
      script:
        - export PYTHONPATH=$PWD:$PYTHONPATH
        - sh -c "cd tests && ./minisciath/minisciath.py tests.yml --only-group default_configuration"
    - stage: lint errors
      python: 2.7
      install:
        - pip install pylint
      script: sh -c "pylint --errors-only sciath/*.py tests/test_data/*/*.py"
    - stage: lint errors
      python: 3.7
      install:
        - pip install pylint
      script: sh -c "pylint --errors-only sciath/*.py tests/test_data/*/*.py"
    - stage: lint all
      python: 3.7
      install:
        - pip install pylint
      script:
        # We include some warning suppression here, as these are too numerous
        # to include individually in the source, and don't even exist for older
        # versions of pylint.
        - sh -c "pylint --disable=consider-using-f-string,unspecified-encoding sciath/*.py"
