language: python

python:
  - "2.7"
  - "3.5"
  - "3.7"

git:
  depth: false

branches:
  only:
    - master
    - dev

install:
  - pip install pyyaml pylint

script:
  - export PYTHONPATH=$PWD:$PYTHONPATH
  - sh -c "cd tests && ./minisciath/minisciath.py tests.yml --only-group default_configuration"
  - sh -c "pylint --errors-only sciath/*.py tests/test_data/*/*.py"
